name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true # Remove if dependencies fail to install

    - name: Run unittests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Install test tools
      run: |
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s env/tests -p "test_*.py"
        coverage report -m
